### ISSUE TITLE
【Design Spec】サイト共通のトランジション設定

### ISSUE THREAD

**Issue by indif78** [uplinkjp/uplink.co.jp#11]
別途指定のない限り、サイト共通のトランジション設定（デフォルト値）は下記が適用されるようにしてください。

```css
.hoge {
  transition-duration: .3s;
  transition-timing-function: cubic-bezier(.8, 0, .3, 1);
}
```
