### ISSUE TITLE
【Design Spec】レイアウトとブレイクポイント

### ISSUE THREAD

**Issue by indif78** [uplinkjp/uplink.co.jp#12]
## 基本方針

本サイトは基本的にモバイル（スマホ）ファーストでデザインしています。
原則として1カラム構造になり、リキッドレイアウトでの実装をお願いいたします。

## リキッドレイアウト

- リキッドレイアウトであっても、各要素のフォントサイズおよび余白は均一の想定です。
- スライダーやお知らせエリアのサムネイルなど画像要素はアスペクト比を維持しながら拡大・縮小するように組み込みをお願いします。（例えばお知らせエリアの記事タイトルエリアとサムネイルエリアの幅は`vw`などで指定するイメージ）

## ブレイクポイント

- `min-width: 768px`と`min-width: 1024px`でブレイクポイントを設けてください。
- 最小Viewport幅は`320px`の想定です（それより狭くなる場合は横スクロールが出る形）。
- Bootstrap的にブレクポイントごとに親コンテナ幅が固定になるのではなく、左右の余白を（ブレイクポイントごとに）一定にし、変動する`width`に応じてその中身がフィットする形としてください。
- 親コンテナ左右の余白量は取り急ぎデザイン通りとなる形としてください。実装を進める中で余白の値を再検討し、確定できるよう、調整しやすい形にしておいていただけると幸いです。
- 親コンテナの`max-width`は取り急ぎ`1280px`としてください（調整の可能性もあり）。

**Comment by indif78** [comment]
@uunnee 
## コンテナ幅の設定値

コンテナ幅ですが、ブレイクポイント`768px`以上では下記の相対値で固定できそうです。
お手数ですが、設定のほどお願いいたします。

```css
@media (min-width: 768px) {
  .container { /* クラス名は適宜 */
    margin: 0 auto;
    width: 87.5vw;
    max-width: 1260px; /* 暫定 */
  }
}
```

`max-width`の値も`1260px`としました。これつまりはウィンドウ幅`1440px`を越えるとそれ以上コンテナ幅が伸びなくなるという想定です。

不明点や問題などありましたらお知らせくださいませ。
