### ISSUE TITLE
【Design Spec】リンクホバー時のデフォルト挙動

### ISSUE THREAD

**Issue by indif78** [uplinkjp/uplink.co.jp#15]
モバイルファーストということで、現時点で特に派手なホバー処理は想定していません。
取り急ぎリンク要素に対してはサイト共通で下記が適用されるようお願いします。

```css
a {
  transition: opacity .225s cubic-bezier(.8, 0, .3, 1); // 早めの速度でサイト共通のイージング値
}
a:hover {
  opacity: .7;
}
```
