### ISSUE TITLE
【共通】font-smoothing設定を追加

### ISSUE THREAD

**Issue by indif78** [uplinkjp/uplink.co.jp#43]
@uunnee 
毎度のおまじない、`font-smoothing`設定を`body`へ追加お願いします。

```css
body {
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
```
